# Generated by Django 4.2.4 on 2023-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=40)),
                ('dname', models.CharField(default='', max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
