# Generated by Django 4.2.4 on 2023-08-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
