# Generated by Django 4.2.4 on 2023-08-27 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_rename_email_doctor_doc_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doc_email',
            new_name='email',
        ),
    ]
